#Sample .travis.yml for R projects

env:
  global:
    - MAKEFLAGS="-j 2"
    - _R_CHECK_FORCE_SUGGESTS=0
language: r
r: 
  - 3.5.2
r_packages:
  - devtools
package: cache
bioc_required: true
r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-manual --timings"
-os:
  - linux
  - osx
before_install:
  Rscript -e 'update.packages(ask = FALSE)'
sudo: required
apt_packages: libudunits2-dev